variables:
  location: 'westus'
  rootManagementGroup: 'ALZ'
  connectivityManagementGroup: 'alz-platform-connectivity'
  identityManagementGroup: 'alz-platform-identity'
  managementManagementGroup: 'alz-platform-management'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Deploy Monitor Policy Definitions'
  inputs:
    azureSubscription: newVSstudio
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     az deployment mg create --template-file '$(System.DefaultWorkingDirectory)/infra-as-code/bicep/deploy_dine_policies.bicep' --location $(location) --management-group-id $(ManagementGroupPrefix)
- task: AzureCLI@2
  displayName: 'Deploy Monitor Policy Initiative Definitions'
  inputs:
    azureSubscription: newVSstudio
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     az deployment mg create --template-file '$(System.DefaultWorkingDirectory)/src/resources/Microsoft.Authorization/policySetDefinitions/ALZ-MonitorConnectivity.json' --location $(location) --management-group-id $(connectivityManagementGroup)
     az deployment mg create --template-file  '$(System.DefaultWorkingDirectory)/src/resources/Microsoft.Authorization/policySetDefinitions/ALZ-MonitorIdentity.json' --location $(location) --management-group-id $(identityManagementGroup)
     az deployment mg create --template-file  '$(System.DefaultWorkingDirectory)/src/resources/Microsoft.Authorization/policySetDefinitions/ALZ-MonitorManagement.json' --location $(location) --management-group-id $(managementManagementGroup)
         
- task: AzureCLI@2
  displayName: 'Assign Policies'
  inputs:
    azureSubscription: newVSstudio
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     az deployment mg create --template-file '$(System.DefaultWorkingDirectory)/infra-as-code/bicep/assign_initiatives_connectivity.bicep' --location $(location) --management-group-id $(connectivityManagementGroup)
     az deployment mg create --template-file  '$(System.DefaultWorkingDirectory)/infra-as-code/bicep/assign_initiatives_identity.bicep' --location $(location) --management-group-id $(identityManagementGroup)
     az deployment mg create --template-file  '$(System.DefaultWorkingDirectory)/infra-as-code/bicep/assign_initiatives_management.bicep' --location $(location) --management-group-id $(managementManagementGroup)
     az deployment mg create --template-file  '$(System.DefaultWorkingDirectory)/infra-as-code/bicep/assign_initiatives_landingzones.bicep --location' --location $(location) --management-group-id $(rootManagementGroup)
